# integrated_manufacturing/value_chain_federated_dp.yaml

# --- CROSS-FUNCTIONAL VALUE CHAIN DATA PRODUCT (Federated) ---
name: "Manufacturing Value Chain Profitability"
description: |
  This federated data product provides a holistic financial view by linking raw material costs (SCM/ERP), manufacturing schedules (MES), and final sales demand (CRM). It is designed for finance and executive teams to monitor performance and strategic alignment.

  **Key Objectives:**
  - **Monitor Profitability:** Analyze the variance between planned costs in ERP and actual purchase prices from suppliers.
  - **Align Production with Demand:** Identify gaps between customer orders and the scheduled production pipeline to mitigate stockout risks.
  - **Analyze Cost Variances:** Quantify the financial impact of component price fluctuations on the cost of goods sold (COGS).

  **Business Questions Answered:**
  1. For which products are we paying significantly more for components than our standard cost estimates?
  2. Are we at risk of a stockout? Which products have the biggest gap between customer orders and scheduled production?
  3. What is the financial impact of the variance between component purchase price and planned cost?
summary: "Views for Cost-of-Goods-Sold and Demand Fulfillment"

# DATA PRODUCT DESTINATION (Schema 3: Federated)
domain: "Integrated Manufacturing"
catalog: ${MANUF_FEDERATED_DP_CATALOG}
schema: ${MANUF_FEDERATED_DP_SCHEMA}

owners:
  - name: "Executive & Finance"
    email: "pascal.gasp@starburstdata.com"

tags:
  - "Federated"
  - "Finance"
  - "Profitability"
  - "COGS"
  - "SCM"
  - "CRM"
  - "Demand Planning"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Total Cost of Finished Goods (ERP/SCM Federation - Stock Management/Cost)
  - name: "v_cost_of_finished_goods"
    description: "Calculates a final cost estimate by federating planned ERP cost, actual SCM purchase cost, and MES efficiency. This view is critical for finance teams to monitor cost of goods sold (COGS) and identify drivers of profit margin erosion."
    security_mode: "INVOKER" 
    
    query: |
      WITH SCMCosts AS (
          SELECT
              PartID,
              AVG(PurchasePrice) AS AvgSCMPurchasePrice,
              AVG(DeliveryLeadTime_Days) AS AvgLeadTime
          FROM ${MANUF_RAW_CATALOG}.${MANUF_RAW_SCHEMA}.scm_supplier_invoices
          GROUP BY 1
      )
      SELECT
          p.PartID,
          p.PartName,
          p.UnitCost_ERP AS PlannedCost_ERP,
          sc.AvgSCMPurchasePrice AS ActualCost_SCM,
          sc.AvgLeadTime AS SupplierLeadTime_Days,
          (sc.AvgSCMPurchasePrice / p.UnitCost_ERP) - 1 AS CostVariance_Pct
      FROM ${MANUF_RAW_CATALOG}.${MANUF_RAW_SCHEMA}.plm_product_master p
      JOIN SCMCosts sc ON p.PartID = sc.PartID
      WHERE p.PartType != 'Raw Material'
      ORDER BY CostVariance_Pct DESC
      
    columns:
      - name: "PartID"
        type: "varchar"
        description: "ID of the component/finished good."
      - name: "PartName"
        type: "varchar"
        description: "The common name of the part."
      - name: "PlannedCost_ERP"
        type: "double"
        description: "Standard unit cost from ERP master data."
      - name: "ActualCost_SCM"
        type: "double"
        description: "Average purchase price based on recent supplier invoices."
      - name: "SupplierLeadTime_Days"
        type: "double"
        description: "Average delivery lead time from suppliers for this part."
      - name: "CostVariance_Pct"
        type: "double"
        description: "Percentage variance between actual purchase cost and planned ERP cost."

  # 2. Demand Fulfillment vs. Production Schedule (CRM/MES Federation - Optimization/Efficiency)
  - name: "v_demand_fulfillment_gap"
    description: "Compares customer demand (CRM) against available production schedule (MES) by Top-Level Part ID. This enables operations teams to proactively identify and address potential stockouts or shortfalls in production capacity."
    security_mode: "INVOKER" 
    
    query: |
      WITH CustomerDemand AS (
          SELECT
              ERP_TopLevelPartID AS PartID,
              SUM(QuantityOrdered) AS TotalDemand
          FROM ${MANUF_RAW_CATALOG}.${MANUF_RAW_SCHEMA}.crm_customer_orders
          GROUP BY 1
      ),
      ProductionSchedule AS (
          SELECT
              TopLevelPartID AS PartID,
              SUM(PlannedQty) AS TotalScheduledProduction
          FROM ${MANUF_RAW_CATALOG}.${MANUF_RAW_SCHEMA}.mes_work_orders
          WHERE Status IN ('Scheduled', 'In_Progress')
          GROUP BY 1
      )
      SELECT
          cd.PartID,
          cd.TotalDemand,
          ps.TotalScheduledProduction,
          ps.TotalScheduledProduction - cd.TotalDemand AS FulfillmentGap
      FROM CustomerDemand cd
      FULL JOIN ProductionSchedule ps ON cd.PartID = ps.PartID
      WHERE ps.TotalScheduledProduction IS NULL OR ps.TotalScheduledProduction < cd.TotalDemand
      ORDER BY FulfillmentGap ASC
      
    columns:
      - name: "PartID"
        type: "varchar"
        description: "ID of the top-level assembly/product."
      - name: "TotalDemand"
        type: "bigint"
        description: "Total quantity demanded by customers (CRM)."
      - name: "TotalScheduledProduction"
        type: "bigint"
        description: "Total quantity scheduled for production (MES)."
      - name: "FulfillmentGap"
        type: "bigint"
        description: "Difference between scheduled production and customer demand (Negative = Risk of Stockout)."
