# --- CUSTOMER ANALYTICS DATA PRODUCT ---
name: "E-Commerce Customer Analytics"
description: "Semantic layer for marketing, CLV calculation, and customer segmentation based on purchase and web behavior."
summary: "Views for Customer Lifetime Value (CLV) and Engagement"

# DATA PRODUCT DESTINATION (Targets the dedicated analytics schema)
domain: "E-Commerce"
catalog: ${ECOMMERCE_ANALYTICS_DP_CATALOG}
schema: ${ECOMMERCE_ANALYTICS_DP_SCHEMA}

owners:
  - name: "Marketing Analytics"
    email: "marketing-team@ecommerce.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Customer Lifetime Value (CLV)
  - name: "v_customer_lifetime_value"
    description: "Calculates total customer spend and purchase frequency for CLV and segmentation."
    security_mode: "INVOKER" 
    
    query: |
      WITH CustomerOrders AS (
          SELECT
              c.CustomerID, -- FIX APPLIED HERE: Qualified column with alias 'c' (for customers)
              COUNT(OrderID) AS TotalOrders,
              SUM(TotalAmount) AS TotalRevenue,
              DATE_DIFF('day', JoinedDate, current_date) AS CustomerAgeDays
          FROM ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.orders o
          JOIN ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.customers c 
              ON o.CustomerID = c.CustomerID
          WHERE OrderStatus = 'Completed'
          GROUP BY 1, 4
      )
      SELECT 
          c.CustomerID,
          co.TotalRevenue,
          co.TotalOrders,
          c.CustomerRegion,
          co.TotalRevenue / CAST(co.CustomerAgeDays AS DOUBLE) * 365.25 AS AnnualizedCLV
      FROM ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.customers c
      JOIN CustomerOrders co ON c.CustomerID = co.CustomerID
    
    columns:
      - name: "CustomerID"
        type: "varchar"
        description: "Unique customer identifier."
      - name: "TotalRevenue"
        type: "double"
        description: "Customer's all-time completed spend."
      - name: "TotalOrders"
        type: "bigint"
        description: "Total number of completed orders."
      - name: "AnnualizedCLV"
        type: "double"
        description: "Estimated annual Customer Lifetime Value based on past spend."

  # 2. Behavioral Engagement (Web Session Metrics)
  - name: "v_customer_web_engagement"
    description: "Aggregates web session activity, conversion funnel steps, and recency of visits."
    security_mode: "INVOKER" 
    
    query: |
      WITH SessionMetrics AS (
          SELECT 
              CustomerID, 
              COUNT(DISTINCT SessionID) AS TotalSessions,
              COUNT(CASE WHEN EventType = 'ProductView' THEN 1 END) AS ProductViews,
              COUNT(CASE WHEN EventType = 'AddToCart' THEN 1 END) AS AddsToCart,
              MAX(SessionStart) AS LastSessionDate
          FROM ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.web_sessions
          WHERE CustomerID IS NOT NULL
          GROUP BY 1
      )
      SELECT 
          sm.CustomerID,
          sm.TotalSessions,
          sm.AddsToCart,
          DATE_DIFF('day', sm.LastSessionDate, NOW()) AS RecencyDays,
          CAST(sm.AddsToCart AS DOUBLE) * 100 / sm.ProductViews AS AddToCartRatePct
      FROM SessionMetrics sm
      WHERE sm.ProductViews > 0
    
    columns:
      - name: "CustomerID"
        type: "varchar"
        description: "Unique customer identifier."
      - name: "TotalSessions"
        type: "bigint"
        description: "Total tracked web sessions."
      - name: "RecencyDays"
        type: "bigint"
        description: "Days since the last recorded web session."
      - name: "AddToCartRatePct"
        type: "double"
        description: "Percentage of product views that result in an 'add to cart' action."