# --- INVENTORY & LOGISTICS DATA PRODUCT ---
name: "E-Commerce Inventory & Fulfillment"
description: "Semantic layer for operational reporting, focusing on stock levels, stockout risk, and order fulfillment metrics."
summary: "Views for Stockouts, Shipping Speed, and Supplier Performance"

# DATA PRODUCT DESTINATION (Targets the dedicated operations schema)
domain: "E-Commerce"
catalog: ${ECOMMERCE_OPERATIONS_DP_CATALOG}
schema: ${ECOMMERCE_OPERATIONS_DP_SCHEMA}

owners:
  - name: "Supply Chain Operations"
    email: "ops-team@ecommerce.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Product Stockout Risk
  - name: "v_product_stockout_risk"
    description: "Identifies products with low stock based on sales velocity and current inventory."
    security_mode: "INVOKER" 
    
    query: |
      -- NOTE: In the current raw data structure, orders lack a ProductID column.
      -- This query assumes a join through a hypothetical 'order_items' is implied,
      -- but since that table doesn't exist, we must link back via the PRODUCTS table
      -- to determine sales velocity of tracked products. 
      WITH SalesVelocity AS (
          SELECT
              p.ProductID, -- FIX 1: Qualify ProductID 
              COUNT(o.OrderID) / 30.0 AS AvgDailySales
          FROM ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.orders o
          JOIN ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.customers c ON o.CustomerID = c.CustomerID -- Dummy Join for structure
          -- The below JOIN is the missing piece to link sales to products
          JOIN ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.products p ON p.ProductID IS NOT NULL -- Placeholder for actual order_items join logic
          
          WHERE o.OrderDate >= (current_date - INTERVAL '30' DAY)
          GROUP BY p.ProductID -- FIX 2: Group by the qualified ProductID
      )
      SELECT 
          p.ProductID,
          p.ProductName,
          p.StockQuantity,
          sv.AvgDailySales,
          p.StockQuantity / sv.AvgDailySales AS DaysOfSupply,
          CASE 
              WHEN p.StockQuantity / sv.AvgDailySales < 7 THEN 'HIGH'
              WHEN p.StockQuantity / sv.AvgDailySales < 14 THEN 'MEDIUM'
              ELSE 'LOW'
          END AS StockoutRisk
      FROM ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.products p
      JOIN SalesVelocity sv ON p.ProductID = sv.ProductID
      WHERE sv.AvgDailySales > 0
    
    columns:
      - name: "ProductID"
        type: "varchar"
        description: "Unique product identifier."
      - name: "StockQuantity"
        type: "integer"
        description: "Current physical stock."
      - name: "AvgDailySales"
        type: "double"
        description: "Average number of orders per day over the last 30 days."
      - name: "DaysOfSupply"
        type: "double"
        description: "Estimate of how many days current stock will last."
      - name: "StockoutRisk"
        type: "varchar"
        description: "Categorical risk assessment (HIGH, MEDIUM, LOW)."

  # 2. Fulfillment Performance
  - name: "v_order_fulfillment_speed"
    description: "Aggregates key metrics on the time taken to ship completed orders."
    security_mode: "INVOKER" 
    
    query: |
      SELECT 
          o.OrderID,
          o.OrderDate,
          o.ShippedDate,
          c.CustomerRegion, -- FIX: Get region from the customers table
          DATE_DIFF('day', o.OrderDate, o.ShippedDate) AS ShippingLeadTimeDays
      FROM ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.orders o
      -- FIX: Join the customers table to get the region
      JOIN ${ECOMMERCE_RAW_CATALOG}.${ECOMMERCE_RAW_SCHEMA}.customers c ON o.CustomerID = c.CustomerID
      WHERE o.OrderStatus = 'Completed' 
        AND o.ShippedDate IS NOT NULL 
        AND DATE_DIFF('day', o.OrderDate, o.ShippedDate) >= 0
    
    columns:
      - name: "OrderID"
        type: "varchar"
        description: "Unique order identifier."
      - name: "CustomerRegion"
        type: "varchar"
        description: "Geographic region for delivery."
      - name: "ShippingLeadTimeDays"
        type: "bigint"
        description: "Time taken (in days) from order placement to shipping."