# --- CIB ESG SEMANTIC LAYER DEFINITION ---
name: "CIB ESG Portfolio Views"
description: "A comprehensive semantic layer focusing on client screening, portfolio risk exposure, and detailed environmental/social metrics."
summary: "Three-Layer Semantic Access to ESG Data"

# DATA PRODUCT DESTINATION (Pulls from your .env variables)
domain: "Risk & Compliance"
catalog: ${ESG_DP_CATALOG} 
schema: ${ESG_DP_SCHEMA}

owners:
  - name: "ESG Reporting Team"
    email: "esg-ops@cibbank.com"

# ==============================================================================
# SEMANTIC VIEWS ONLY (Multiple Layers)
# ==============================================================================
views:
  # --- Layer 1: Portfolio Context and Risk Screening ---
  - name: "v_portfolio_client_risk"
    description: "Links active financing deals to client entity data and their latest overall ESG score for risk screening."
    security_mode: "INVOKER" 
    
    query: |
      WITH LatestRating AS (
          SELECT
              r.ClientID, r.OverallScore, r.EScore, r.GScore, r."Date",
              ROW_NUMBER() OVER(PARTITION BY r.ClientID ORDER BY r."Date" DESC) as rn
          FROM ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.esg_ratings r 
      )
      SELECT 
          d.DealID,
          d.DealType,
          d.Amount,
          d.Sector,
          c.CompanyName,
          c.Industry,
          lr.OverallScore AS LatestESGScore,
          lr.EScore
      FROM ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.financing_deals d
      JOIN ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.client_entities c ON d.ClientID = c.ClientID
      LEFT JOIN LatestRating lr ON c.ClientID = lr.ClientID AND lr.rn = 1
      WHERE d.DealType IN ('Loan', 'Bond') -- Focus on debt exposure
    
    columns:
      - name: "DealID"
        type: "varchar"
        description: "Identifier for the financing transaction."
      - name: "Amount"
        type: "double"
        description: "Total size of the financing deal, used for exposure calculation."
      - name: "CompanyName"
        type: "varchar"
        description: "Name of the financed client entity."
      - name: "Industry"
        type: "varchar"
        description: "Industry of the client entity."
      - name: "LatestESGScore"
        type: "double"
        description: "Client's most recent overall ESG rating (0-100)."


  # --- Layer 2: Granular Social and Governance Metrics (Deep Dive) ---
views:
  - name: "v_client_social_governance_detail"
    description: "Detailed, unaggregated view of social and governance metrics for due diligence and internal reporting."
    security_mode: "INVOKER" 
    
    query: |
      SELECT 
          c.ClientID,
          c.CompanyName,
          s.DiversityScore,
          s.EmployeeTurnover,
          g.BoardDiversityPct,
          g.CEO_PayRatio,
          g.AuditCommitteeIndependence
      FROM ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.client_entities c
      LEFT JOIN ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.s_metrics s ON c.ClientID = s.ClientID
      LEFT JOIN ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.g_metrics g ON c.ClientID = g.ClientID
      WHERE s.DiversityScore IS NOT NULL -- Focus on entities with reported social data
    
    columns:
      - name: "ClientID"
        type: "varchar"
        description: "Unique identifier for the client."
      - name: "DiversityScore"
        type: "double"
        description: "Score or percentage representing workforce diversity."
      - name: "EmployeeTurnover"
        type: "double"
        description: "Annual rate of employee turnover (ratio)."
      - name: "BoardDiversityPct"
        type: "double"
        description: "Percentage of board members identifying as diverse."
      - name: "CEO_PayRatio"
        type: "integer"
        description: "Ratio of CEO compensation to median employee compensation."


  # --- Layer 3: Environmental Metrics and Financed Emissions ---
views:
  - name: "v_financed_emissions_metrics"
    description: "Calculates the final environmental exposure for regulatory reporting (PCAF/financed emissions)."
    security_mode: "INVOKER" 
    
    query: |
      SELECT 
          d.DealID,
          d.DealDate,
          d.Amount,
          d.UseOfProceeds,
          e.GHG_Emissions_Scope1,
          e.EnergyMix_Renewable,
          -- Final calculated exposure metric
          (d.Amount * e.GHG_Emissions_Scope1) AS WeightedGHGExposure 
      FROM ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.financing_deals d
      JOIN ${ESG_RAW_CATALOG}.${ESG_RAW_SCHEMA}.e_metrics e ON d.DealID = e.DealID
      WHERE e.GHG_Emissions_Scope1 IS NOT NULL
      
    columns:
      - name: "DealID"
        type: "varchar"
        description: "Financing transaction ID."
      - name: "Amount"
        type: "double"
        description: "Total size of the deal."
      - name: "UseOfProceeds"
        type: "varchar"
        description: "Stated purpose of the deal (e.g., Renewable Energy Project)."
      - name: "GHG_Emissions_Scope1"
        type: "double"
        description: "Client's direct greenhouse gas emissions (metric tons CO2e)."
      - name: "EnergyMix_Renewable"
        type: "double"
        description: "Percentage of client's energy consumption sourced from renewable energy."
      - name: "WeightedGHGExposure"
        type: "double"
        description: "The calculated financed emissions risk metric."