# automotive/factory_efficiency_data_product.yaml

# --- FACTORY OPTIMIZATION DATA PRODUCT ---
name: "Auto Manufacturing Factory Efficiency"
description: "Semantic layer for measuring production run efficiency, identifying assembly bottlenecks, and tracking rework rates."
summary: "Views for Production Bottlenecks and Throughput"

# DATA PRODUCT DESTINATION (Schema 2: Efficiency)
domain: "Automotive Manufacturing"
catalog: ${AUTOMOTIVE_EFFICIENCY_DP_CATALOG}
schema: ${AUTOMOTIVE_EFFICIENCY_DP_SCHEMA}

owners:
  - name: "Production Engineering"
    email: "engineering@auto-corp.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Assembly Step Bottlenecks
  - name: "v_assembly_step_bottlenecks"
    description: "Calculates the average duration and rework rate for each assembly step."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          StepName,
          LineID,
          AVG(DATE_DIFF('minute', StartTime, EndTime)) AS AvgStepDuration_min,
          SUM(CASE WHEN IsRework = TRUE THEN 1 ELSE 0 END) AS TotalReworkCount,
          CAST(SUM(CASE WHEN IsRework = TRUE THEN 1 ELSE 0 END) AS DOUBLE) * 100 / COUNT(StepID) AS ReworkRate_Pct
      FROM ${AUTOMOTIVE_RAW_CATALOG}.${AUTOMOTIVE_RAW_SCHEMA}.assembly_steps
      WHERE EndTime IS NOT NULL
      GROUP BY 1, 2
      ORDER BY AvgStepDuration_min DESC
      
    columns:
      - name: "StepName"
        type: "varchar"
        description: "Name of the assembly stage (e.g., Engine Install, Paint Booth)."
      - name: "LineID"
        type: "varchar"
        description: "Identifier for the production line."
      - name: "AvgStepDuration_min"
        type: "double"
        description: "Average time taken to complete this step."
      - name: "ReworkRate_Pct"
        type: "double"
        description: "Percentage of runs requiring rework at this step."

  # 2. Production Run Variance
  - name: "v_production_run_variance"
    description: "Compares the actual total build time to the target time per production run Model."
    security_mode: "INVOKER" 
    
    query: |
      WITH ActualBuildTime AS (
          SELECT
              RunID,
              DATE_DIFF('hour', MIN(StartTime), MAX(EndTime)) AS ActualTime_hrs
          FROM ${AUTOMOTIVE_RAW_CATALOG}.${AUTOMOTIVE_RAW_SCHEMA}.assembly_steps
          GROUP BY 1
      )
      SELECT
          pr.RunID,
          pr.Model,
          pr.TargetBuildTime_hrs,
          abt.ActualTime_hrs,
          abt.ActualTime_hrs - pr.TargetBuildTime_hrs AS TimeVariance_hrs,
          CASE
              WHEN abt.ActualTime_hrs > pr.TargetBuildTime_hrs * 1.10 THEN 'SLOW'
              WHEN abt.ActualTime_hrs < pr.TargetBuildTime_hrs * 0.90 THEN 'FAST'
              ELSE 'ON_TARGET'
          END AS PerformanceStatus
      FROM ${AUTOMOTIVE_RAW_CATALOG}.${AUTOMOTIVE_RAW_SCHEMA}.production_runs pr
      JOIN ActualBuildTime abt ON pr.RunID = abt.RunID
      
    columns:
      - name: "RunID"
        type: "varchar"
        description: "Unique production run identifier."
      - name: "Model"
        type: "varchar"
        description: "The vehicle model being produced."
      - name: "TargetBuildTime_hrs"
        type: "integer"
        description: "Predefined target time for the full assembly."
      - name: "ActualTime_hrs"
        type: "bigint"
        description: "Actual total time spent on assembly."
      - name: "TimeVariance_hrs"
        type: "bigint"
        description: "Difference between actual and target time."