# automotive/quality_control_data_product.yaml

# --- QUALITY CONTROL DATA PRODUCT ---
name: "Auto Manufacturing Quality & Sensor"
description: "Semantic layer for analyzing sensor data, tracking anomalies, and providing input for process quality improvement."
summary: "Views for Sensor Anomaly Detection and Quality Metrics"

# DATA PRODUCT DESTINATION (Schema 3: Quality)
domain: "Automotive Manufacturing"
catalog: ${AUTOMOTIVE_QUALITY_DP_CATALOG}
schema: ${AUTOMOTIVE_QUALITY_DP_SCHEMA}

owners:
  - name: "Quality Assurance Team"
    email: "qa@auto-corp.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Real-time Anomaly Rate
  - name: "v_sensor_anomaly_rate"
    description: "Calculates the percentage of sensor readings flagged as anomalous over the last hour, broken down by sensor type and assembly step."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          SensorType,
          AssemblyStep,
          COUNT(ReadingID) AS TotalReadings,
          SUM(CASE WHEN IsAnomaly = TRUE THEN 1 ELSE 0 END) AS AnomalyCount,
          CAST(SUM(CASE WHEN IsAnomaly = TRUE THEN 1 ELSE 0 END) AS DOUBLE) * 100 / COUNT(ReadingID) AS AnomalyRate_Pct
      FROM ${AUTOMOTIVE_RAW_CATALOG}.${AUTOMOTIVE_RAW_SCHEMA}.quality_sensor_data
      WHERE MeasurementTime >= (NOW() - INTERVAL '1' HOUR)
      GROUP BY 1, 2
      HAVING COUNT(ReadingID) > 100 -- Focus on active reporting segments
      ORDER BY AnomalyRate_Pct DESC
      
    columns:
      - name: "SensorType"
        type: "varchar"
        description: "Type of sensor (e.g., Vibration, Torque)."
      - name: "AssemblyStep"
        type: "varchar"
        description: "The assembly step where the sensor was used."
      - name: "TotalReadings"
        type: "bigint"
        description: "Total number of readings in the period."
      - name: "AnomalyRate_Pct"
        type: "double"
        description: "Percentage of readings flagged as anomalous."

  # 2. Final Inspection Quality Rollup
  - name: "v_final_inspection_quality"
    description: "Rolls up the number of critical anomalies per final product run."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          pr.RunID,
          pr.VIN_Serial,
          pr.Model,
          COUNT(qsd.ReadingID) AS TotalAnomaliesDetected
      FROM ${AUTOMOTIVE_RAW_CATALOG}.${AUTOMOTIVE_RAW_SCHEMA}.production_runs pr
      JOIN ${AUTOMOTIVE_RAW_CATALOG}.${AUTOMOTIVE_RAW_SCHEMA}.quality_sensor_data qsd ON pr.RunID = qsd.RunID
      WHERE qsd.IsAnomaly = TRUE
      GROUP BY 1, 2, 3
      HAVING COUNT(qsd.ReadingID) > 5 -- Focus on runs with significant issues
      
    columns:
      - name: "RunID"
        type: "varchar"
        description: "Unique production run identifier."
      - name: "VIN_Serial"
        type: "varchar"
        description: "The vehicle's serial number."
      - name: "Model"
        type: "varchar"
        description: "Vehicle model."
      - name: "TotalAnomaliesDetected"
        type: "bigint"
        description: "Total count of sensor anomalies flagged for this run."