# tms/financial_carrier_data_product.yaml

# --- FINANCIAL & CARRIER PERFORMANCE DATA PRODUCT ---
name: "TMS Financial & Carrier Performance"
description: "Semantic layer for tracking costs, invoicing status, and rating carrier performance."
summary: "Views for Cost Analysis and Carrier Rating"

# DATA PRODUCT DESTINATION (Schema 2: Financial)
domain: "Transportation Management"
catalog: ${TMS_FINANCIAL_DP_CATALOG}
schema: ${TMS_FINANCIAL_DP_SCHEMA}

owners:
  - name: "Finance & Procurement"
    email: "finance@tms.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Calculate Cost Per Mile by Route Type
  - name: "v_cost_per_mile_analysis"
    description: "Calculates total cost per planned mile, aggregated by the Origin-Destination Region combination."
    security_mode: "INVOKER" 
    
    query: |
      WITH TripCosts AS (
          SELECT
              t.TripID,
              t.PlannedDistance_mi,
              t.OriginRegion,
              t.DestinationRegion,
              SUM(i.TotalInvoiceAmount) AS TotalCost
          FROM ${TMS_RAW_CATALOG}.${TMS_RAW_SCHEMA}.trips t
          JOIN ${TMS_RAW_CATALOG}.${TMS_RAW_SCHEMA}.invoices i ON t.TripID = i.TripID
          GROUP BY 1, 2, 3, 4
      )
      SELECT
          tc.OriginRegion,
          tc.DestinationRegion,
          SUM(tc.TotalCost) AS AggregatedCost,
          SUM(tc.PlannedDistance_mi) AS AggregatedDistance,
          SUM(tc.TotalCost) / NULLIF(SUM(tc.PlannedDistance_mi), 0) AS CostPerMile
      FROM TripCosts tc
      WHERE tc.PlannedDistance_mi > 0
      GROUP BY 1, 2
      HAVING SUM(tc.PlannedDistance_mi) > 1000 
      ORDER BY CostPerMile DESC
      
    columns:
      - name: "OriginRegion"
        type: "varchar"
        description: "Starting region of the trip."
      - name: "DestinationRegion"
        type: "varchar"
        description: "Ending region of the trip."
      - name: "AggregatedCost"
        type: "double"
        description: "Total invoiced cost for all trips on this route."
      - name: "CostPerMile"
        type: "double"
        description: "Calculated aggregated cost divided by aggregated planned miles."

  # 2. Rate Carrier On-Time Performance (OTP)
  - name: "v_carrier_on_time_performance"
    description: "Calculates the percentage of on-time trips (defined as 0-minute delay or early) for each carrier."
    security_mode: "INVOKER" 
    
    query: |
      WITH TripPerformance AS (
          SELECT
              v.CarrierID,
              t.TripID,
              CASE
                  WHEN DATE_DIFF('minute', t.PlannedDeliveryTime, t.ActualDeliveryTime) <= 0 THEN 1 -- On-Time or Early
                  ELSE 0
              END AS IsOnTime
          FROM ${TMS_RAW_CATALOG}.${TMS_RAW_SCHEMA}.trips t
          JOIN ${TMS_RAW_CATALOG}.${TMS_RAW_SCHEMA}.vehicles v ON t.VehicleID = v.VehicleID
          WHERE t.TripStatus IN ('Completed', 'Delayed') AND t.ActualDeliveryTime IS NOT NULL
      )
      SELECT
          tp.CarrierID,
          COUNT(tp.TripID) AS TotalTripsCompleted,
          SUM(tp.IsOnTime) AS OnTimeTrips,
          CAST(SUM(tp.IsOnTime) AS DOUBLE) * 100 / COUNT(tp.TripID) AS OnTimePerformance_Pct
      FROM TripPerformance tp
      GROUP BY 1
      HAVING COUNT(tp.TripID) >= 100 
      ORDER BY OnTimePerformance_Pct DESC
      
    columns:
      - name: "CarrierID"
        type: "varchar"
        description: "The unique identifier for the logistics provider."
      - name: "TotalTripsCompleted"
        type: "bigint"
        description: "Total completed trips used in the calculation."
      - name: "OnTimeTrips"
        type: "bigint"
        description: "Number of trips that arrived on time or early."
      - name: "OnTimePerformance_Pct"
        type: "double"
        description: "Percentage of trips delivered on time."