# telecom/bss_data_product.yaml

# --- BSS (Business Support System) DATA PRODUCT ---
name: "Telecom BSS Revenue & Billing"
description: "Semantic layer for tracking customer segments, subscription status, revenue recognition, and invoice aging."
summary: "Views for Revenue Segmentation and Billing Health"

# DATA PRODUCT DESTINATION (Schema 2: BSS)
domain: "Telecom"
catalog: ${TELECOM_BSS_DP_CATALOG}
schema: ${TELECOM_BSS_DP_SCHEMA}

owners:
  - name: "Finance & Billing Team"
    email: "billing@telecom.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. Monthly Revenue by Segment and Product
  - name: "v_revenue_segmentation"
    description: "Aggregated monthly recurring revenue by customer segment and product type."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          t.ProductID,
          c.CustomerSegment,
          COUNT(t.SubscriptionID) AS ActiveSubscriptions,
          SUM(t.MonthlyFee) AS TotalMRR
      FROM ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.service_subscriptions t
      JOIN ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.customers c ON t.CustomerID = c.CustomerID
      WHERE t.ContractStatus = 'Active'
      GROUP BY 1, 2
      ORDER BY 4 DESC
      
    columns:
      - name: "ProductID"
        type: "varchar"
        description: "The specific product (e.g., Mobile-Pro, Fiber-Gold)."
      - name: "CustomerSegment"
        type: "varchar"
        description: "Customer type (e.g., Residential, Business-SME)."
      - name: "ActiveSubscriptions"
        type: "bigint"
        description: "Count of currently active subscriptions."
      - name: "TotalMRR"
        type: "double"
        description: "Total Monthly Recurring Revenue."

  # 2. Overdue Invoice Aging
  - name: "v_overdue_invoice_aging"
    description: "Lists outstanding invoices categorized by days overdue."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          i.InvoiceID,
          i.AmountDue,
          i.DaysLate,
          s.ProductID,
          c.CustomerSegment,
          CASE
              WHEN i.DaysLate BETWEEN 1 AND 30 THEN '01-30 Days Late'
              WHEN i.DaysLate BETWEEN 31 AND 90 THEN '31-90 Days Late'
              ELSE '90+ Days Late'
          END AS AgingBucket
      FROM ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.invoices i
      JOIN ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.service_subscriptions s ON i.SubscriptionID = s.SubscriptionID
      JOIN ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.customers c ON s.CustomerID = c.CustomerID
      WHERE i.PaymentStatus = 'Overdue' AND i.DaysLate > 0
      ORDER BY i.DaysLate DESC
      
    columns:
      - name: "InvoiceID"
        type: "varchar"
        description: "Unique invoice identifier."
      - name: "AmountDue"
        type: "double"
        description: "The amount outstanding."
      - name: "DaysLate"
        type: "integer"
        description: "Number of days the invoice is overdue."
      - name: "AgingBucket"
        type: "varchar"
        description: "Categorical aging bucket for the invoice."