# telecom/oss_data_product.yaml

# --- OSS (Operations Support System) DATA PRODUCT ---
name: "Telecom OSS Network Health"
description: "Semantic layer for monitoring network performance, service quality, and fault detection across cell sites."
summary: "Views for Network Performance and Fault Analysis"

# DATA PRODUCT DESTINATION (Schema 1: OSS)
domain: "Telecom"
catalog: ${TELECOM_OSS_DP_CATALOG}
schema: ${TELECOM_OSS_DP_SCHEMA}

owners:
  - name: "Network Operations Team"
    email: "netops@telecom.com"

# ==============================================================================
# SEMANTIC VIEWS
# ==============================================================================
views:
  
  # 1. High Latency Cell Sites (Service Quality Degradation)
  - name: "v_cell_site_latency_health"
    description: "Identifies cell sites with consistently high latency and packet loss over the last hour."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          CellSiteID,
          AVG(Latency_ms) AS AvgLatency,
          AVG(PacketLoss_Pct) AS AvgPacketLoss,
          COUNT(RecordID) AS MeasurementCount
      FROM ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.network_performance
      WHERE "Timestamp" >= (NOW() - INTERVAL '1' HOUR) -- Trino syntax for interval
      GROUP BY 1
      HAVING AVG(Latency_ms) > 100 OR AVG(PacketLoss_Pct) > 2
      
    columns:
      - name: "CellSiteID"
        type: "varchar"
        description: "Identifier for the network equipment location."
      - name: "AvgLatency"
        type: "double"
        description: "Average network latency in milliseconds over the reporting period."
      - name: "AvgPacketLoss"
        type: "double"
        description: "Average packet loss percentage."
      - name: "MeasurementCount"
        type: "bigint"
        description: "Number of performance records used in the average."

  # 2. Critical Fault Summary
  - name: "v_critical_fault_summary"
    description: "Summary of currently open Critical faults, including average resolution time."
    security_mode: "INVOKER" 
    
    query: |
      SELECT
          CellSiteID,
          COUNT(FaultID) AS CriticalFaultCount,
          AVG(ResolutionTime_min) AS AvgResolutionTime_min
      FROM ${TELECOM_RAW_CATALOG}.${TELECOM_RAW_SCHEMA}.fault_records
      WHERE Severity = 'Critical'
      GROUP BY 1
      ORDER BY 2 DESC
      
    columns:
      - name: "CellSiteID"
        type: "varchar"
        description: "Identifier for the network equipment location."
      - name: "CriticalFaultCount"
        type: "bigint"
        description: "Count of critical faults logged."
      - name: "AvgResolutionTime_min"
        type: "double"
        description: "Average time taken to resolve the critical faults in minutes."